### ISSUE TITLE
Sorting doesn't always result in a fully sorted inventory

### ISSUE THREAD

**Issue by machasins** [sakura-ryoko/itemscroller#22] opened 2024-10-03 23:27 UTC
With some configurations of items, inventories need to be sorted multiple times to result in a actually sorted set of items. This is most common when removing two stacks of items from a chest, sorting the chest, and then re-adding the stacks. The sorting seems to only switch the last non-empty slots of the chest with where the items should be, and doesn't continue sorting from there.

![javaw_8voULZNjnm](https://github.com/user-attachments/assets/5765c367-154d-48c1-a6ae-ff689f4a53e2)
(Note: You can see when the hotkey is used by the contents of the shulker changing, two of the shulkers change places with every sort because they have the same fill level)

The same kind of behavior can be observed in reverse when taking out a single stack of items, and trying to sort it then.

![javaw_q2qOrIdpgJ](https://github.com/user-attachments/assets/aa0b1f9e-606d-4711-b20a-83f2a0c4add9)

There is also a smaller issue with items that have the same name, or shulkers that have the same level of fullness (as can be seen in both images). They get offset from their original position by one when repeatedly sorting an inventory. I feel that this could be fixed by offering an option for a secondary sorting priority, or just fixed secondary sorting of Raw ID (or the Raw ID of the first item in a shulker?).

I'd also like to ask for an option to remove the requirement for you to be hovered over an item before sorting the inventory, or at least have it be an option. Also an option for sorting by TOTAL item count, and not just stack size, would be nice.

Thanks 😄

**Comment by sakura-ryoko** [comment] 2024-10-09 18:18
Are you using the most recent Github version ?

https://github.com/sakura-ryoko/itemscroller/releases/tag/1.21-0.24.1-sakura.3

**Comment by Xalum** [comment] 2024-10-09 21:19
I'm not machasins but I can confirm this happening on the latest Github version. I also second their opinion to revert the requirement to be hovering over an item instead of just the inventory panel

https://github.com/user-attachments/assets/92a3991c-9d96-45aa-b12b-3b9004fe19a3

**Comment by machasins** [comment] 2024-10-09 21:35
I can confirm that this is happening with the most recent version.

**Comment by sakura-ryoko** [comment] 2024-10-24 03:08
Try it with 1.21.3.

**Comment by machasins** [comment] 2024-10-24 05:23
![javaw_yjOb60ys9S](https://github.com/user-attachments/assets/3e122a54-5de4-48e9-af08-e3c8598a9c87)

This issue has not been resolved with the update.
(video made with only malilib and itemscroller installed in MC1.21.3)

**Comment by sakura-ryoko** [comment] 2024-10-24 18:40
Can you figure out which blocks in particular are causing this behavior ?  Spawn Eggs, Spawners, etc ?

Also show your Sorting Mode.

**Comment by machasins** [comment] 2024-10-24 20:34
All items cause this issue, I can't find an item that doesn't. Sorting mode also doesn't impact this issue, it happens no matter what mode it is set to. I believe all previous clips were with 'Item Name' sorting, although that might have changed with testing.

[Here's](https://youtu.be/1yfFFGzyJIo) a video showing that the item type and sorting method really doesn't stop it from occurring. 

It takes more sort button presses to resolve the inventory when the item taken out is near the first inventory slot, so that's the slot I take from the most. I tried to get a variety of items and demonstrate the bug in all of the sorting modes. I also showed all my settings.
(I only have malilib and itemscroller installed in this video, on MC1.21.3)

Also, changing the sorting mode can result in a [similar issue](https://youtu.be/Asb9Rf2a5G0) where the inventory isn't sorted after one keypress.

**Comment by sakura-ryoko** [comment] 2024-12-05 23:53
Hello, I've made another attempt at fixing this problem.  This time, I know what the cause was; because like I said before; I had to add various mitigation code into the mod to stop infinite loops; which was the original problems with `sortInventory`.  One of those mechanisms was a Task Cancel when it detects if the same 'swap' is repeated. (A <-> B, then B <-> A); where this can legitimately happen with how this is coded if the items are named the same; for example with Spawn Eggs all having the same name; where then the sorting task needs to rely on other factors, such as Item Count or Raw Item ID hash values after attempting to sort based on the name.

So, what I did for this update, was to add a 'repeat counter' with a limit of repeated swaps, and whenever the swap is different at all, it resets the counter back to 0.  A Task Cancel will *only* ever occur if the mod tries swapping (A <-> B, then B <-> A) a total of 4 times in a row.  If this is even different by 1, then the counter gets reset.

What was happening in some of these videos was the results of Task Cancellation code trying to protect the mod from causing those Infinite Loops; where the sources of those Loops has been fixed / mitigated by other means than a simple "repeated swap counting" check; which was part of my previous efforts.

Please try the new code and seeing if you can repeat the above.  I have tested it with like 8 spawn eggs and other Random junk in a Shulker Box, and regular chest.  I have not had sorting failures like I was having before with these items; with my own testing under the newer code from today.

**Comment by sakura-ryoko** [comment] 2024-12-06 00:01
@Xalum @machasins

**Comment by sakura-ryoko** [comment] 2024-12-11 16:54
No additional comments, I'll close this.

**Closed as completed by sakura-ryoko** 2024-12-11 16:54 UTC
Labels: bug, fixed
